### ISSUE TITLE
formatTime parsing incorrectly?

### ISSUE THREAD

**Issue by Tetracyl** [Solaris9/erela.js#29]
When the milliseconds parameter is less than 60 seconds, it returns `ss`, when it should return `00:ss` because when the milliseconds parameter is 60 seconds or more, it returns `mm:ss`.

**Comment by WarHammer414** [comment]
That's how the parser works but [this](https://github.com/WarHammer414/erela.js/blob/rewrite/src/structures/Utils.ts#L128) in the rewrite will fix that.
