### ISSUE TITLE
Can't open documentation website

### ISSUE THREAD

**Issue by Knatschkopp** [Solaris9/erela.js#40]
Hey, today I wanted to take a look into the documentation of erela.js but the domain to the website doesn't work anymore. Looking around I found that you are working on a new version of erela.js and that you have a new website. Could you by any chance reupload the old erela documentation?

**Comment by IF64** [comment]
solaris announced docs are back up on his  new domains https://projects.solaris.codes/erelajs/ https://projects.solaris.codes/erelajs-rewrite/
