### ISSUE TITLE
Error: getaddrinfo ENOTFOUND https

### ISSUE THREAD

**Issue by ustokan** [Solaris9/erela.js#41]
![image](https://user-images.githubusercontent.com/55207603/91070513-7fd1b780-e63f-11ea-8477-a773caaed19c.png)

**Comment by ustokan** [comment]
![image](https://user-images.githubusercontent.com/55207603/91070654-b4de0a00-e63f-11ea-9fbf-92de9c53d120.png)

**Comment by Solaris9** [comment]
This is most likely user error, please join the [Discord server](https://discord.com/invite/5dTpady) for further assistance as Github issues are for actual bugs within the code.
