### ISSUE TITLE
<Queue>.remove does not work

### ISSUE THREAD

**Issue by inhydrox** [Solaris9/erela.js#43]
Hey <Queue>.remove does not work 
![Image](https://user-images.githubusercontent.com/40756526/91632242-34335b00-e9fd-11ea-8476-5ac2d0883614.gif)

**Comment by inhydrox** [comment]
My erela version: 2.0.0-beta.5

**Comment by Anish-Shobith** [comment]
It's impossible to say with the amount of information you provided please link code or provide code for us to reproduce the issue

**Comment by inhydrox** [comment]
```js
     const amount = Math.round(Number(args[0]) || 0) - 1;   
     
     player.queue.remove(amount);
```

**Comment by Solaris9** [comment]
I am unable to reproduce this with my code, are you able to provide your own code so I can test it?

**Comment by Anish-Shobith** [comment]
Closing this issue , if the issue persist please re open the issue and provide more code for us to check.
