### ISSUE TITLE
queueEnd event does not emit when a song is skipped 

### ISSUE THREAD

**Issue by AnejP** [Solaris9/erela.js#47]
Whenever you skip the last song in the queue the queueEnd event does not emit.

**Comment by chroventer** [comment]
Can you provide code to reproduce this error?

**Comment by AnejP** [comment]
Here is the skip command I use :

`const BaseCommand = require('../../utils/structures/BaseCommand');
const { musicneigra, musickanal } = require('../../utils/embeds');

module.exports = class SkipCommand extends BaseCommand {
  constructor() {
    super('skip', 'glasba', []);
  }

  run(client, message, args) {
    message.delete({ timeout: 100 });
    const player = client.manager.players.get(message.guild.id);
    if (!player || player.queue.size == 0) return message.channel.send(musicneigra).then(d_msg => {d_msg.delete({ timeout: 5000 })});
    const { channel } = message.member.voice;
    if (!channel || player.voiceChannel !== channel.id) return message.channel.send(musickanal).then(d_msg => {d_msg.delete({ timeout: 5000 })});
    player.stop();
  }
}`

**Comment by JustAPieOP** [comment]
well, the queueEnd only emits when the queue has nothing inside i guess?

**Comment by Anish-Shobith** [comment]
Your code seems to have fault in here queue is a typeof Array not a Map so basically `.size` doesn't exit on the array its `.length` which gives you the length of the array

**Comment by AnejP** [comment]
It is in the [documentation](https://projects.solaris.codes/erelajs-rewrite/docs/classes/Queue.html#size) and it works.

**Comment by Anish-Shobith** [comment]
Alright it seems that change was made from length to size. Have you tried manually emitting the event to see if that works?

**Comment by AnejP** [comment]
No, but the event does emit when the song finishes playing it just dosen't emit when it is skipped.

**Comment by karelkryda** [comment]
Same problem

**Comment by karelkryda** [comment]
@Solaris9 no solution?

**Comment by Solaris9** [comment]
The latest commit should have the fix for that from my testing but best to see from who knows about it, you can test it to see if it still happens. Install it using `npm i Solaris9/erela.js#build`, you will need Git for this.

**Comment by karelkryda** [comment]
> The latest commit should have the fix for that from my testing but best to see from who knows about it, you can test it to see if it still happens. Install it using `npm i Solaris9/erela.js#build`, you will need Git for this.

@Solaris9 It's working now...thanks
