### ISSUE TITLE
Audio not playing in voice channel.

### ISSUE THREAD

**Issue by Volcie** [Solaris9/erela.js#48]
### Hi guys!
I've been really excited to use this library.

Today I decided to code a music category for my bot.
But unfortunately, When ever I tell a player to play the current queue.. It doesn't play the audio in the voice channel.

Here is my code:
```js
const { voice } = message.member;
    if(voice.channel){
        var player = this.client.music.players.spawn({
                textChannel: message.channel,
                guild: message.guild,
                voiceChannel: voice.channel
        });
        var searchResults = await this.client.music.search(args.query, message.author);
        //console.log(searchResults);
        player.queue.add(searchResults.tracks[0]);
        console.log(player.queue);
        player.play()
```

The track is added to the queue, everything works fine for now.. Till `player.play()` is executed! It actually emit the event `trackStart` but it doesn't play audio in the voice channel.
I've tried discord.js [music code from the guides](https://discordjs.guide/popular-topics/miscellaneous-examples.html#play-music-from-youtube), It worked.

**Note: I'm using __`discord-akairo`__ framework for my bot.**

Thanks in advance. ;)

**Comment by SerenModz21** [comment]
Make sure you have Java 11 or greater and have the latest lavalink build.

I have Java 13 from [Zulu](https://www.azul.com/downloads/zulu-community/?architecture=x86-64-bit&package=jdk) of which I installed with [SDKMAN](https://sdkman.io/).

**Comment by Volcie** [comment]
I have `java@11.0.8`.
And about lavalink I downloaded it from [here](https://www.npmjs.com/package/erela.js-rewrite).
Which I guess it's pretty good for erela right now.

BTW I think this is because `discord-akairo` (The framework i'm using for my bot) but actually I don't know where the problem is exactly!

**Comment by AbdualmalikQ** [comment]
Make sure that you send the voice data to lavalink:
`client.on("raw", d => client.music.updateVoiceState(d));`

**Comment by Solaris9** [comment]
> Make sure that you send the voice data to lavalink:
> 
> ```js
> client.on("raw", d => client.music.updateVoiceState(d));
> ```
They are using stable, not rewrite, I don't see any reason why this wouldn't work since stable handles everything for you while rewrite you have to pass the data to and from Erela.js yourself, it would be easier to know what the issue is if we had logs from Lavalink.

**Comment by Volcie** [comment]
@AbdualmalikQ I have tried it anyways, It still not working.. Same issue as i described above.

**Comment by Volcie** [comment]
Even the green circle around the bot's avatar is not showing.

**Comment by Volcie** [comment]
Should I try `erela.js-rewrite`?

**Comment by Solaris9** [comment]
Rewrite was just released so I would recommend updating Erela.js and see if this still happens.

You can update normally like so `npm i erela.js` or `yarn add erela.js`

- Documentaion: https://projects.solaris.codes/erelajs/docs/gettingstarted.html
- Guides: https://projects.solaris.codes/erelajs/guides/introduction.html
- Examples: https://github.com/Solaris9/erela.js/tree/master/examples

**Comment by Anish-Shobith** [comment]
V2 was just launched yesterday or today (time zone) and previous version was 1.1.8 itself
