### ISSUE TITLE
queue.remove(start,end) not working

### ISSUE THREAD

**Issue by karelkryda** [Solaris9/erela.js#53]
Hi, I'm trying to use `player.queue.remove(start, end)`.
Unfortunately, if I give the number 0 as the start, I get an `error missing start parameter`. If I enter the number 1 instead of start, I get an `error start parameter cannot be bigger then 0`.

I am doing something wrong?
Why can't I remove a range like this from start index 5 to end index 10, for example?

**Comment by JustAPieOP** [comment]
use `.slice(start, end)` instead

**Comment by karelkryda** [comment]
Fixed in the latest release
