### ISSUE TITLE
Playlist sorting

### ISSUE THREAD

**Issue by karelkryda** [Solaris9/erela.js#54]
The playlist is not sorted by YouTube order.

**Comment by Solaris9** [comment]
I have no control over that, lavaplayer searches and returns the playlist which Erela sends to the user.

**Comment by karelkryda** [comment]
Oh...ok

So what would I do?

**Comment by Solaris9** [comment]
I'm not sure, it could be that version of lavalink, or it could be something else, Node.JS keeps the insertion so it must be on lavalinks end, testing it anyway shows the correct order. Because of that I'm closing this.
