### ISSUE TITLE
Music sometimes doesn't start playing

### ISSUE THREAD

**Issue by karelkryda** [Solaris9/erela.js#55]
Me again.
If I call the play command, the music sometimes doesn't start playing. I have to call the command again and the music will start playing.
I enclose the Lavalink log screenshot.

![image](https://user-images.githubusercontent.com/59953812/97434709-b4a00a80-191f-11eb-8453-9807eebfe574.png)

**Comment by Solaris9** [comment]
I believe that's something on YouTubes end, you can try downloading the latest version of [Lavalink](https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1). I would also add the [trackError event](https://projects.solaris.codes/erelajs/docs/classes/Manager.html#trackerror) which will run whenever there's a error while playing a track.
