### ISSUE TITLE
issue with pausing the player

### ISSUE THREAD

**Issue by ParasDeshpande** [Solaris9/erela.js#58]
An empty player with no playing audio can be unpaused and will play nothing and player.playing will be true
This happens when a track is added to the  queue while the player is not playing. When you resume the player gets stuck at that position since there is no way to find out from the player if it is playing audio or not... Player.playing returns true and player.queue.current returns the track that was added while the player was not playing.

**Comment by karelkryda** [comment]
Disable pause when the queue is empty

**Comment by ParasDeshpande** [comment]
But what if there is nothing playing but because of the new added track the queue is not empty so you can still unpause... But there is no way to find out if the track has started playing after unpausing from the player itself...

**Comment by Solaris9** [comment]
> Disable pause when the queue is empty

This wont work if they call Player#pause() after.

I'll make it not let you pause or resume when the queue is empty because there's no point when it's empty.

**Comment by inhydrox** [comment]
> But what if there is nothing playing but because of the new added track the queue is not empty so you can still unpause... But there is no way to find out if the track has started playing after unpausing from the player itself...

Player#playing returns a boolean value whether the player is pause or not
