### ISSUE TITLE
Documentation website isn't running

### ISSUE THREAD

**Issue by DynamoYT** [Solaris9/erela.js#69]
![Screenshot 2020-11-23 193004](https://user-images.githubusercontent.com/63182360/99970805-5e10d980-2dc2-11eb-844a-6903df2b8cd1.png)

**Comment by Solaris9** [comment]
The link was changed to https://solaris.codes/projects/erelajs to work with my site redesign, the NPM pages haven't been updated because it's just a url, there will be some bug fixes and when those are out the link will be updated.
