### ISSUE TITLE
Major issue with Connecting/Disconnecting from node

### ISSUE THREAD

**Issue by CyberCDN** [Solaris9/erela.js#70]
For some strange reason if the doesn't use the music that often and the you try to use it again, it says `No available Nodes` yet there is in both the Manager and the node is alive.

**Comment by Solaris9** [comment]
Can you give an estimated time frame? What do you mean the manager says the node is still alive? [Node#connected](https://github.com/Solaris9/erela.js/blob/master/src/structures/Node.ts#L76-L79) shows if the node is connected or not, this is called basically every time you try to any action with the node, I'm not sure how it could be connected but also say it's not connected. It could have been a network issue between the two for being idle so long and the websocket didn't update the readyState but I don't know without more information.
