### ISSUE TITLE
Enhancement:  SkipTo utility

### ISSUE THREAD

**Issue by mcdaddytalk** [Solaris9/erela.js#73]
Would like to be able to issue skipto to jump queue to given track number of queue

**Comment by Solaris9** [comment]
This was added in 2.3.0, `Player#stop(index: number)` takes an index to skip to, meaning if you provide `5` it will stop the current song, the next 4, and play the 5th.

**Comment by mcdaddytalk** [comment]
Updated to 2.3.0, 

Const track = args[0];
If (isNaN(track)) return;

Player.stop(track);

Current track is skipped but does not progress by index.  Simply progresses to next song 

---------------------
Best Regards,
Karlan Talkington

"If there must be trouble, let it be in my day so that my children may live free." ~ Thomas Paine

**Comment by Solaris9** [comment]
`Player#stop(index: number)` requires a number, you are most likely not providing a number.
