### ISSUE TITLE
Cannot search tracks via link

### ISSUE THREAD

**Issue by DMNight6** [Solaris9/erela.js#75]
The error returned in d.js is 400 (Bad request).
Lavalink returned the error where the identifier cannot be found.

**Comment by Solaris9** [comment]
I need the full error to be able to do anything.

**Comment by DMNight6** [comment]
Solaris, Lavalink or d.js?

**Comment by DMNight6** [comment]
Lavalink : 2020-12-28 19:20:30.414  WARN 11024 --- [ XNIO-1 task-26] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'identifier' is not present]

d.js : (node:268) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (C:\Users\arnok\OneDrive\Desktop\Bots item\Bot\Lavalink-JS\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\arnok\OneDrive\Desktop\Bots item\Bot\Lavalink-JS\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\arnok\OneDrive\Desktop\Bots item\Bot\Lavalink-JS\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Solaris9** [comment]
Neither of these are helpful, Lavalink should have more info about the error, Discord.JS has nothing to do with this, what you mean is Node.JS, and that still doesn't help me as it doesn't say what it's from other than some request failed, it could be anything. Show more of the error or any code that goes with the error.

**Comment by DMNight6** [comment]
module.exports = {
    name: 'play',
    description: 'play {args}',
    async execute(client, message, args) {
        const res = await client.Music.search(
            query = args,
            requester = message.author
        );

        const player = client.Music.create({
            guild: message.guild.id,
            voiceChannel: message.member.voice.channel.id,
            textChannel: message.channel.id,
        });

        player.connect();
        if (res.LoadType == "PLAYLIST_LOADED") {
            for (res in res.tracks) {
                player.queue.add(res)
            }
            message.channel.send(`Enqueuing ${res.playlist.title}`)
        } else {
            console.log(`${res.tracks}`)
            player.queue.add(res.tracks[0])
            message.channel.send(`Enqueuing Track ${res.tracks[0].title}`)
        }

        if (!player.playing) {player.play();}
    }
}

**Comment by DMNight6** [comment]
if args is a link, lavalink only returns the error [WARN 11024 --- [ XNIO-1 task-26] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'identifier' is not present]]

**Comment by DMNight6** [comment]
if you need my base code, I can upload it right here

**Comment by DMNight6** [comment]
C:\Users\arnok\OneDrive\Desktop\Bots item\Bot\Lavalink-JS\d.js

**Comment by Solaris9** [comment]
It would be best if you sent the code as it without screen shots so I can copy and paste to test it, but I see what why anyway, you're passing an array when it needs to be a string, join the arguments before searching. I'll add some type checks for searching for the next update.
